logging:
  file: log/chat.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    com.project: debug
  server:
    port: 8080
    servlet:
      context-path: /
  #Enabling GZip compression
    compression:
      enabled: true
      mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
      min-response-size: 1024
  #Enabling HTTP/2 support
    http2:
        enabled: true